name = "local-event-discovery"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
routes = [
  { pattern = "findernyc.com", custom_domain = true },
  { pattern = "www.findernyc.com", custom_domain = true },
  { pattern = "hiddencitygems.com", custom_domain = true },
  { pattern = "www.hiddencitygems.com", custom_domain = true },
  { pattern = "experiences.miami", custom_domain = true },
  { pattern = "www.experiences.miami", custom_domain = true },
  { pattern = "mmeexx.com", custom_domain = true },
  { pattern = "www.mmeexx.com", custom_domain = true },
]

[[d1_databases]]
binding = "DB"
database_name = "findernyc-production"
database_id = "b646d8fe-ed7f-458b-936b-15f91b5e6016"
preview_database_id = "6640508c-3bd9-413f-8ba5-f35d99f46223"
migrations_dir = "src/db/migrations"

[assets]
directory = "src/assets"
binding = "ASSETS"
