name = "local-event-discovery"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
routes = [
  { pattern = "findernyc.com", custom_domain = true },
  { pattern = "www.findernyc.com", custom_domain = true },
  { pattern = "hiddencitygems.com", custom_domain = true },
  { pattern = "www.hiddencitygems.com", custom_domain = true },
  { pattern = "experiences.miami", custom_domain = true },
  { pattern = "www.experiences.miami", custom_domain = true },
  { pattern = "mmeexx.com", custom_domain = true },
  { pattern = "www.mmeexx.com", custom_domain = true },
]

[[d1_databases]]
binding = "DB"
database_name = "findernyc-production"
database_id = "3b28bfa8-4eb9-4c1e-a342-a5557fb79344"
preview_database_id = "0400aca1-b8b3-46d8-9d19-3f8d1efaf16d"
migrations_dir = "src/db/migrations"

[assets]
directory = "src/assets"
binding = "ASSETS"
