import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';

export const DEFAULT_EXPORT_PATH = 'output/d1-migration/source-export.json';
export const DEFAULT_IMPORT_SQL_PATH = 'output/d1-migration/d1-import.sql';

export const TABLE_SPECS = [
  {
    name: 'leads',
    columns: [
      ['id', (row) => row.id],
      ['email', (row) => row.email],
      ['source_cta', (row) => row.source_cta],
      ['source_section', (row) => row.source_section],
      ['use_case', (row) => row.use_case],
      ['team_size', (row) => row.team_size],
      ['city', (row) => row.city],
      ['borough', (row) => row.borough],
      ['created_at', (row) => toTimestampMs(row.created_at)],
    ],
  },
  {
    name: 'waitlist_entries',
    columns: [
      ['id', (row) => row.id],
      ['email', (row) => row.email],
      ['zip_code', (row) => row.zip_code],
      ['city', (row) => row.city],
      ['use_case', (row) => row.use_case],
      ['team_size', (row) => row.team_size],
      ['goal', (row) => row.goal],
      ['follow_up_route', (row) => row.follow_up_route],
      ['follow_up_priority', (row) => row.follow_up_priority],
      ['follow_up_status', (row) => row.follow_up_status],
      ['created_at', (row) => toTimestampMs(row.created_at)],
    ],
  },
  {
    name: 'analytics_events',
    columns: [
      ['id', (row) => row.id],
      ['event_name', (row) => row.event_name],
      ['properties', (row) => toJsonColumn(row.properties)],
      ['session_id', (row) => row.session_id],
      ['created_at', (row) => toTimestampMs(row.created_at)],
    ],
  },
  {
    name: 'saved_searches',
    columns: [
      ['id', (row) => row.id],
      ['query_text', (row) => row.query_text],
      ['filters', (row) => toJsonColumn(row.filters)],
      ['channel', (row) => row.channel],
      ['destination', (row) => row.destination],
      ['session_id', (row) => row.session_id],
      ['is_active', (row) => toSqlBoolean(row.is_active)],
      ['created_at', (row) => toTimestampMs(row.created_at)],
    ],
  },
  {
    name: 'alert_delivery_attempts',
    columns: [
      ['id', (row) => row.id],
      ['saved_search_id', (row) => row.saved_search_id],
      ['channel', (row) => row.channel],
      ['provider', (row) => row.provider],
      ['delivery', (row) => row.delivery],
      ['success', (row) => toSqlBoolean(row.success)],
      ['attempt_count', (row) => row.attempt_count],
      ['status_code', (row) => row.status_code],
      ['error', (row) => row.error],
      ['created_at', (row) => toTimestampMs(row.created_at)],
    ],
  },
];

export function ensureParent(path) {
  mkdirSync(dirname(path), { recursive: true });
}

export function readJson(path) {
  return JSON.parse(readFileSync(path, 'utf8'));
}

export function writeJson(path, value) {
  ensureParent(path);
  writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`, 'utf8');
}

export function writeText(path, value) {
  ensureParent(path);
  writeFileSync(path, `${value.endsWith('\n') ? value : `${value}\n`}`, 'utf8');
}

export function toTimestampMs(value) {
  if (value === null || value === undefined || value === '') return null;

  if (typeof value === 'number') {
    if (value > 1_000_000_000_000) return Math.trunc(value);
    if (value > 1_000_000_000) return Math.trunc(value * 1000);
    return Math.trunc(value);
  }

  if (value instanceof Date) {
    return value.getTime();
  }

  const stringValue = String(value).trim();
  if (/^\d+$/.test(stringValue)) {
    return toTimestampMs(Number(stringValue));
  }

  const parsed = Date.parse(stringValue);
  if (!Number.isFinite(parsed)) {
    throw new Error(`Unable to convert timestamp value "${stringValue}" to milliseconds`);
  }

  return parsed;
}

export function toSqlBoolean(value) {
  if (value === null || value === undefined || value === '') return null;
  if (typeof value === 'boolean') return value ? 1 : 0;
  if (typeof value === 'number') return value === 0 ? 0 : 1;

  const normalized = String(value).trim().toLowerCase();
  if (['1', 'true', 't', 'yes', 'y'].includes(normalized)) return 1;
  if (['0', 'false', 'f', 'no', 'n'].includes(normalized)) return 0;

  throw new Error(`Unable to convert boolean value "${value}" to SQLite integer`);
}

export function toJsonColumn(value) {
  if (value === null || value === undefined || value === '') return null;
  return JSON.stringify(value);
}

export function toSqlLiteral(value) {
  if (value === null || value === undefined) return 'NULL';
  if (typeof value === 'number') {
    if (!Number.isFinite(value)) return 'NULL';
    return String(value);
  }
  return `'${String(value).replaceAll("'", "''")}'`;
}

export function buildImportSql(payload) {
  const lines = [
    '-- Generated by scripts/d1/build-d1-import-sql.mjs',
    `-- Source export generated at: ${payload.exportedAt ?? 'unknown'}`,
    'BEGIN TRANSACTION;',
    '',
    "DELETE FROM alert_delivery_attempts;",
    "DELETE FROM saved_searches;",
    "DELETE FROM analytics_events;",
    "DELETE FROM waitlist_entries;",
    "DELETE FROM leads;",
    "DELETE FROM sqlite_sequence WHERE name IN ('alert_delivery_attempts', 'saved_searches', 'analytics_events', 'waitlist_entries', 'leads');",
    '',
  ];

  for (const table of TABLE_SPECS) {
    const rows = Array.isArray(payload.tables?.[table.name]) ? payload.tables[table.name] : [];

    lines.push(`-- ${table.name}: ${rows.length} row(s)`);

    for (const row of rows) {
      const columnNames = table.columns.map(([columnName]) => `\`${columnName}\``).join(', ');
      const values = table.columns
        .map(([, getter]) => toSqlLiteral(getter(row)))
        .join(', ');
      lines.push(`INSERT INTO \`${table.name}\` (${columnNames}) VALUES (${values});`);
    }

    const maxId = rows.reduce((max, row) => {
      const id = Number(row.id ?? 0);
      return Number.isFinite(id) ? Math.max(max, Math.trunc(id)) : max;
    }, 0);

    if (maxId > 0) {
      lines.push(`INSERT INTO sqlite_sequence(name, seq) VALUES ('${table.name}', ${maxId});`);
    }

    lines.push('');
  }

  lines.push('COMMIT;');
  return `${lines.join('\n')}\n`;
}
