import { initContract } from '@ts-rest/core';
import { z } from 'zod';

const c = initContract();

export const contract = c.router({
  getRuntimeConfig: {
    method: 'GET',
    path: '/api/config',
    responses: {
      200: z.object({
        feature_flags: z.record(z.boolean()),
        analytics: z.object({
          ga4_measurement_id: z.string().optional(),
          segment_write_key: z.string().optional(),
          providers: z.object({
            ga4: z.boolean(),
            segment: z.boolean(),
          }),
        }),
        generated_at: z.string(),
      }),
    },
  },
  unifiedSmartSearch: {
    method: 'POST',
    path: '/api/search',
    body: z.object({
      query: z.string(),
      filters: z.object({
        borough: z.enum(['manhattan', 'brooklyn', 'queens', 'bronx', 'staten_island']).optional(),
        category: z.enum(['music', 'food', 'arts', 'networking', 'family', 'wellness']).optional(),
        max_price: z.number().optional(),
        starts_before_hour: z.number().optional(),
        within_walk_minutes: z.number().optional(),
      }).optional(),
      commute_profile: z.object({
        home_borough: z.enum(['manhattan', 'brooklyn', 'queens', 'bronx', 'staten_island']).optional(),
        work_borough: z.enum(['manhattan', 'brooklyn', 'queens', 'bronx', 'staten_island']).optional(),
        profile_anchor: z.enum(['home', 'work', 'balanced']).optional(),
        departure_hour: z.number().optional(),
      }).optional(),
      neighborhood_profile: z.object({
        preferred_vibes: z.array(
          z.enum(['creative', 'family', 'foodie', 'professional', 'quiet', 'nightlife', 'wellness']),
        ).optional(),
        preferred_boroughs: z.array(z.enum(['manhattan', 'brooklyn', 'queens', 'bronx', 'staten_island'])).optional(),
        crowd_tolerance: z.enum(['low', 'medium', 'high']).optional(),
        budget_preference: z.enum(['free', 'value', 'premium']).optional(),
      }).optional(),
      compare_event_ids: z.array(z.string()).max(3).optional(),
      session_id: z.string().optional(),
      limit: z.number().optional(),
    }),
    responses: {
      200: z.object({
        success: z.literal(true),
        query: z.string(),
        inferred_filters: z.object({
          borough: z.string().optional(),
          category: z.string().optional(),
          max_price: z.number().optional(),
          starts_before_hour: z.number().optional(),
          within_walk_minutes: z.number().optional(),
        }),
        applied_filters: z.object({
          borough: z.string().optional(),
          category: z.string().optional(),
          max_price: z.number().optional(),
          starts_before_hour: z.number().optional(),
          within_walk_minutes: z.number().optional(),
        }),
        results: z.array(z.object({
          id: z.string(),
          organizer_id: z.string(),
          title: z.string(),
          description: z.string(),
          borough: z.string(),
          category: z.string(),
          price: z.number(),
          start_hour: z.number(),
          walk_minutes: z.number(),
          venue: z.string(),
          relevance_score: z.number(),
          availability: z.object({
            status: z.enum(['available', 'limited', 'sold_out']),
            seats_total: z.number().optional(),
            seats_remaining: z.number().optional(),
            updated_at: z.string(),
          }).optional(),
          commute: z.object({
            eta_minutes: z.number(),
            score: z.number(),
            band: z.enum(['excellent', 'good', 'fair', 'poor']),
            mode: z.enum(['walk', 'subway', 'multi_leg']),
            confidence: z.literal('estimated'),
            origin_borough: z.string().optional(),
            profile_anchor: z.enum(['home', 'work', 'balanced']).optional(),
            personalized: z.boolean(),
          }).optional(),
          neighborhood_fit: z.object({
            score: z.number(),
            band: z.enum(['strong', 'moderate', 'weak']),
            dominant_vibe: z.enum(['creative', 'family', 'foodie', 'professional', 'quiet', 'nightlife', 'wellness']),
            reasons: z.array(z.string()),
            personalized: z.boolean(),
          }).optional(),
          personalization: z.object({
            score: z.number(),
            boost: z.number(),
            reasons: z.array(z.string()),
            personalized: z.boolean(),
          }).optional(),
          best_value: z.object({
            score: z.number(),
            band: z.enum(['excellent', 'good', 'fair', 'low']),
            factors: z.object({
              relevance: z.number(),
              affordability: z.number(),
              commute: z.number(),
            }),
          }).optional(),
          ranking_strategy: z.enum(['baseline', 'personalized', 'best_value', 'personalized_best_value']).optional(),
          verification: z.object({
            status: z.enum(['verified', 'pending', 'unverified']),
            badge_label: z.string(),
            verified_at: z.string().optional(),
            verification_method: z.enum(['manual', 'trusted_partner', 'document_check']).optional(),
            trust_score: z.number(),
          }).optional(),
          fraud_risk: z.object({
            score: z.number(),
            band: z.enum(['low', 'medium', 'high']),
            review_route: z.enum(['allow', 'review_queue', 'block']),
            reasons: z.array(z.string()),
            rules_triggered: z.array(z.string()),
            model_version: z.string(),
          }).optional(),
          review_authenticity: z.object({
            score: z.number(),
            band: z.enum(['trusted', 'mixed', 'suspicious']),
            review_count: z.number(),
            visible_review_count: z.number(),
            suppressed_review_count: z.number(),
            suppression_applied: z.boolean(),
            reasons: z.array(z.string()),
          }).optional(),
          experiment_tags: z.array(z.string()).optional(),
          price_breakdown: z.object({
            base_price: z.number(),
            service_fee: z.number(),
            tax: z.number(),
            total_price: z.number(),
            currency: z.literal('USD'),
            pricing_profile: z.object({
              scope: z.enum(['default', 'organizer']),
              organizer_id: z.string().optional(),
            }),
            disclaimer: z.string(),
          }).optional(),
        })),
        comparison: z.object({
          items: z.array(z.object({
            id: z.string(),
            title: z.string(),
            borough: z.string(),
            category: z.string(),
            price: z.number(),
            start_hour: z.number(),
            walk_minutes: z.number(),
            relevance_score: z.number(),
            total_price: z.number().optional(),
            commute_eta_minutes: z.number().optional(),
            best_value_score: z.number().optional(),
          })),
          summary: z.object({
            compared_count: z.number(),
            cheapest_event_id: z.string().optional(),
            earliest_event_id: z.string().optional(),
            shortest_walk_event_id: z.string().optional(),
            top_relevance_event_id: z.string().optional(),
          }),
        }).optional(),
        experiments: z.array(z.object({
          id: z.enum(['ranking_blend_v1', 'trust_controls_v1']),
          variant: z.enum(['control', 'treatment']),
          guardrail_status: z.enum(['insufficient_sample', 'healthy', 'stop_loss_triggered']),
          rollback_recommended: z.boolean(),
          min_sample_size: z.number(),
          observed_sample_size: z.number(),
        })).optional(),
        total: z.number(),
      }),
      422: z.object({ success: z.literal(false), error: z.string() }),
      503: z.object({ success: z.literal(false), error: z.literal('feature_disabled') }),
    },
  },
  getExperimentsStatus: {
    method: 'GET',
    path: '/api/experiments/status',
    responses: {
      200: z.object({
        success: z.literal(true),
        items: z.array(z.object({
          id: z.enum(['ranking_blend_v1', 'trust_controls_v1']),
          name: z.string(),
          status: z.enum(['active', 'paused', 'rolled_back']),
          settings: z.object({
            treatment_share: z.number(),
            min_sample_size: z.number(),
            stop_loss_delta: z.number(),
            forced_variant: z.enum(['control', 'treatment']).optional(),
          }),
          metrics: z.object({
            control: z.object({
              exposures: z.number(),
              clicks: z.number(),
            }),
            treatment: z.object({
              exposures: z.number(),
              clicks: z.number(),
            }),
            control_ctr: z.number(),
            treatment_ctr: z.number(),
          }),
          guardrail: z.object({
            status: z.enum(['insufficient_sample', 'healthy', 'stop_loss_triggered']),
            rollback_recommended: z.boolean(),
          }),
        })),
      }),
      503: z.object({ success: z.literal(false), error: z.literal('feature_disabled') }),
    },
  },
  rollbackExperiment: {
    method: 'POST',
    path: '/api/experiments/:id/rollback',
    body: z.object({
      reason: z.string().optional(),
    }),
    responses: {
      200: z.object({
        success: z.literal(true),
        item: z.object({
          id: z.enum(['ranking_blend_v1', 'trust_controls_v1']),
          status: z.enum(['active', 'paused', 'rolled_back']),
        }).passthrough(),
        reason: z.string().optional(),
      }),
      404: z.object({ success: z.literal(false), error: z.literal('not_found') }),
      422: z.object({ success: z.literal(false), error: z.string() }),
      503: z.object({ success: z.literal(false), error: z.literal('feature_disabled') }),
    },
  },
  getFraudDashboard: {
    method: 'GET',
    path: '/api/fraud/dashboard',
    responses: {
      200: z.object({
        success: z.literal(true),
        queue_size: z.number(),
        pending_count: z.number(),
        high_risk_pending_count: z.number(),
        reviewed_count: z.number(),
        false_positive_count: z.number(),
        false_positive_rate: z.number(),
        outcomes: z.object({
          cleared: z.number(),
          confirmed_fraud: z.number(),
          false_positive: z.number(),
        }),
      }),
      503: z.object({ success: z.literal(false), error: z.literal('feature_disabled') }),
    },
  },
  listFraudReviewQueue: {
    method: 'GET',
    path: '/api/fraud/review-queue',
    responses: {
      200: z.object({
        success: z.literal(true),
        items: z.array(z.object({
          event_id: z.string(),
          title: z.string(),
          organizer_id: z.string(),
          risk_score: z.number(),
          risk_band: z.enum(['low', 'medium', 'high']),
          review_route: z.enum(['allow', 'review_queue', 'block']),
          reasons: z.array(z.string()),
          status: z.enum(['pending', 'cleared', 'confirmed_fraud', 'false_positive']),
          reviewer: z.string().optional(),
          notes: z.string().optional(),
          created_at: z.string(),
          updated_at: z.string(),
        })),
      }),
      503: z.object({ success: z.literal(false), error: z.literal('feature_disabled') }),
    },
  },
  decideFraudReviewQueueItem: {
    method: 'POST',
    path: '/api/fraud/review-queue/:event_id/decision',
    body: z.object({
      decision: z.enum(['cleared', 'confirmed_fraud', 'false_positive']),
      reviewer: z.string().optional(),
      notes: z.string().optional(),
    }),
    responses: {
      200: z.object({
        success: z.literal(true),
        item: z.object({
          event_id: z.string(),
          status: z.enum(['pending', 'cleared', 'confirmed_fraud', 'false_positive']),
          updated_at: z.string(),
        }).passthrough(),
      }),
      404: z.object({ success: z.literal(false), error: z.literal('not_found') }),
      422: z.object({ success: z.literal(false), error: z.string() }),
      503: z.object({ success: z.literal(false), error: z.literal('feature_disabled') }),
    },
  },
  createSavedSearch: {
    method: 'POST',
    path: '/api/saved-searches',
    body: z.object({
      query_text: z.string(),
      filters: z.object({
        borough: z.enum(['manhattan', 'brooklyn', 'queens', 'bronx', 'staten_island']).optional(),
        category: z.enum(['music', 'food', 'arts', 'networking', 'family', 'wellness']).optional(),
      }).optional(),
      channel: z.enum(['email', 'sms', 'push']).optional(),
      destination: z.string().optional(),
      session_id: z.string().optional(),
    }),
    responses: {
      201: z.object({
        success: z.literal(true),
        id: z.number(),
        delivery: z.enum(['stub', 'queued']),
      }),
      422: z.object({ success: z.literal(false), error: z.string() }),
      503: z.object({ success: z.literal(false), error: z.literal('feature_disabled') }),
    },
  },
  listSavedSearches: {
    method: 'GET',
    path: '/api/saved-searches',
    responses: {
      200: z.object({
        success: z.literal(true),
        items: z.array(z.object({
          id: z.number(),
          query_text: z.string(),
          channel: z.string(),
          destination: z.string().nullable().optional(),
          is_active: z.boolean(),
          created_at: z.date().nullable().optional(),
        })),
      }),
      503: z.object({ success: z.literal(false), error: z.literal('feature_disabled') }),
    },
  },
  sendSavedSearchAlert: {
    method: 'POST',
    path: '/api/saved-searches/:id/send-alert',
    body: z.object({}),
    responses: {
      200: z.object({
        success: z.literal(true),
        id: z.number(),
        delivery: z.enum(['stub', 'queued']),
        provider: z.string(),
        attempt_count: z.number(),
        status_code: z.number().optional(),
        selected_channel: z.enum(['email', 'sms', 'push']).optional(),
        channel_attempts: z.array(z.object({
          channel: z.enum(['email', 'sms', 'push']),
          success: z.boolean(),
          provider: z.string(),
          delivery: z.enum(['stub', 'queued']),
          attempt_count: z.number(),
          status_code: z.number().optional(),
          message_id: z.string().optional(),
          error: z.string().optional(),
          latency_ms: z.number().optional(),
        })).optional(),
        slo_alerts: z.array(z.string()).optional(),
        sent_at: z.string(),
      }),
      404: z.object({ success: z.literal(false), error: z.literal('not_found') }),
      422: z.object({ success: z.literal(false), error: z.string() }),
      502: z.object({
        success: z.literal(false),
        error: z.string(),
        provider: z.string(),
        delivery: z.enum(['stub', 'queued']),
        attempt_count: z.number(),
        status_code: z.number().optional(),
        selected_channel: z.enum(['email', 'sms', 'push']).optional(),
        channel_attempts: z.array(z.object({
          channel: z.enum(['email', 'sms', 'push']),
          success: z.boolean(),
          provider: z.string(),
          delivery: z.enum(['stub', 'queued']),
          attempt_count: z.number(),
          status_code: z.number().optional(),
          message_id: z.string().optional(),
          error: z.string().optional(),
          latency_ms: z.number().optional(),
        })).optional(),
        slo_alerts: z.array(z.string()).optional(),
      }),
      503: z.object({ success: z.literal(false), error: z.literal('feature_disabled') }),
    },
  },
  listSavedSearchDeliveryAttempts: {
    method: 'GET',
    path: '/api/saved-searches/:id/delivery-attempts',
    responses: {
      200: z.object({
        success: z.literal(true),
        items: z.array(z.object({
          id: z.number(),
          provider: z.string(),
          success: z.boolean(),
          delivery: z.string(),
          attempt_count: z.number(),
          status_code: z.number().nullable().optional(),
          error: z.string().nullable().optional(),
          created_at: z.date().nullable().optional(),
        })),
      }),
      422: z.object({ success: z.literal(false), error: z.string() }),
      503: z.object({ success: z.literal(false), error: z.literal('feature_disabled') }),
    },
  },
  getInquiryProfile: {
    method: 'GET',
    path: '/api/inquiries/profile',
    query: z.object({
      session_id: z.string().optional(),
    }),
    responses: {
      200: z.object({
        success: z.literal(true),
        profile: z.object({
          full_name: z.string().optional(),
          email: z.string().optional(),
          phone: z.string().optional(),
          preferred_contact_channel: z.enum(['email', 'sms', 'phone']).optional(),
          note: z.string().optional(),
        }).nullable(),
      }),
      503: z.object({ success: z.literal(false), error: z.literal('feature_disabled') }),
    },
  },
  createOneClickInquiry: {
    method: 'POST',
    path: '/api/inquiries/one-click',
    body: z.object({
      event_id: z.string(),
      session_id: z.string().optional(),
      autofill_from_session: z.boolean().optional(),
      profile: z.object({
        full_name: z.string().optional(),
        email: z.string().optional(),
        phone: z.string().optional(),
        preferred_contact_channel: z.enum(['email', 'sms', 'phone']).optional(),
        note: z.string().optional(),
      }).optional(),
      message: z.string().optional(),
    }),
    responses: {
      201: z.object({
        success: z.literal(true),
        inquiry: z.object({
          id: z.string(),
          event_id: z.string(),
          event_title: z.string(),
          organizer_id: z.string(),
          session_id: z.string().optional(),
          profile: z.object({
            full_name: z.string(),
            email: z.string(),
            phone: z.string().optional(),
            preferred_contact_channel: z.enum(['email', 'sms', 'phone']),
            note: z.string().optional(),
          }),
          message: z.string().optional(),
          status: z.literal('submitted'),
          created_at: z.string(),
        }),
        autofill_profile: z.object({
          full_name: z.string(),
          email: z.string(),
          phone: z.string().optional(),
          preferred_contact_channel: z.enum(['email', 'sms', 'phone']),
          note: z.string().optional(),
        }),
      }),
      404: z.object({ success: z.literal(false), error: z.literal('event_not_found') }),
      422: z.object({
        success: z.literal(false),
        error: z.string(),
        profile: z.object({
          full_name: z.string().optional(),
          email: z.string().optional(),
          phone: z.string().optional(),
          preferred_contact_channel: z.enum(['email', 'sms', 'phone']).optional(),
          note: z.string().optional(),
        }).optional(),
      }),
      503: z.object({ success: z.literal(false), error: z.literal('feature_disabled') }),
    },
  },
  syncCalendarSchedule: {
    method: 'POST',
    path: '/api/scheduling/calendar-sync',
    body: z.object({
      inquiry_id: z.string(),
      event_id: z.string(),
      session_id: z.string().optional(),
      provider: z.enum(['google_calendar', 'outlook_calendar', 'apple_calendar']),
      start_at: z.string(),
      end_at: z.string(),
      timezone: z.string().optional(),
      notes: z.string().optional(),
    }),
    responses: {
      201: z.object({
        success: z.literal(true),
        schedule: z.object({
          id: z.string(),
          inquiry_id: z.string(),
          event_id: z.string(),
          session_id: z.string().optional(),
          provider: z.enum(['google_calendar', 'outlook_calendar', 'apple_calendar']),
          start_at: z.string(),
          end_at: z.string(),
          timezone: z.string(),
          external_event_id: z.string(),
          delivery: z.enum(['stub', 'queued']),
          status_code: z.number().optional(),
          calendar_url: z.string().optional(),
          created_at: z.string(),
        }),
        conflict_checks: z.object({
          conflict_count: z.number(),
          checked_scheduled_sessions: z.number(),
          checked_busy_windows: z.number(),
        }),
      }),
      404: z.object({ success: z.literal(false), error: z.literal('inquiry_not_found') }),
      409: z.object({
        success: z.literal(false),
        error: z.literal('schedule_conflict'),
        conflicts: z.array(z.object({
          source: z.enum(['scheduled_session', 'busy_window']),
          start_at: z.string(),
          end_at: z.string(),
          label: z.string().optional(),
        })),
      }),
      422: z.object({ success: z.literal(false), error: z.string() }),
      502: z.object({
        success: z.literal(false),
        error: z.string(),
        provider: z.enum(['google_calendar', 'outlook_calendar', 'apple_calendar']),
        delivery: z.enum(['stub', 'queued']),
        status_code: z.number().optional(),
      }),
      503: z.object({ success: z.literal(false), error: z.literal('feature_disabled') }),
    },
  },
  aiConciergeChat: {
    method: 'POST',
    path: '/api/ai/concierge',
    body: z.object({
      query: z.string(),
      session_id: z.string().optional(),
      retrieval_limit: z.number().optional(),
      filters: z.object({
        borough: z.enum(['manhattan', 'brooklyn', 'queens', 'bronx', 'staten_island']).optional(),
        category: z.enum(['music', 'food', 'arts', 'networking', 'family', 'wellness']).optional(),
        max_price: z.number().optional(),
        starts_before_hour: z.number().optional(),
        within_walk_minutes: z.number().optional(),
      }).optional(),
    }),
    responses: {
      200: z.object({
        success: z.literal(true),
        answer: z.string(),
        citations: z.array(z.object({
          event_id: z.string(),
          title: z.string(),
          borough: z.string(),
          category: z.string(),
          reason: z.string(),
        })),
        telemetry: z.object({
          prompt_version: z.string(),
          model_version: z.string(),
          fallback_used: z.boolean(),
          fallback_reason: z.string().optional(),
          retrieval_count: z.number(),
        }),
        quality: z.object({
          rubric: z.object({
            scores: z.array(z.object({
              category: z.enum(['grounding', 'clarity', 'actionability', 'safety']),
              score: z.number(),
              rationale: z.string(),
            })),
            overall_score: z.number(),
            band: z.enum(['high', 'medium', 'low']),
          }),
          sampled_for_review: z.boolean(),
          review_sample_id: z.string().optional(),
          sampling_reason: z.enum(['low_quality', 'random_sample']).optional(),
        }),
      }),
      422: z.object({
        success: z.literal(false),
        error: z.string(),
        safety: z.object({
          safe: z.boolean(),
          reason: z.string().optional(),
          matched_term: z.string().optional(),
        }).optional(),
      }),
      503: z.object({ success: z.literal(false), error: z.literal('feature_disabled') }),
    },
  },
  aiShortlistBuilder: {
    method: 'POST',
    path: '/api/ai/shortlist',
    body: z.object({
      intent: z.string(),
      session_id: z.string().optional(),
      max_items: z.number().optional(),
      filters: z.object({
        borough: z.enum(['manhattan', 'brooklyn', 'queens', 'bronx', 'staten_island']).optional(),
        category: z.enum(['music', 'food', 'arts', 'networking', 'family', 'wellness']).optional(),
        max_price: z.number().optional(),
        starts_before_hour: z.number().optional(),
        within_walk_minutes: z.number().optional(),
      }).optional(),
    }),
    responses: {
      200: z.object({
        success: z.literal(true),
        shortlist: z.array(z.object({
          event_id: z.string(),
          title: z.string(),
          borough: z.string(),
          category: z.string(),
          price: z.number(),
          start_hour: z.number(),
          walk_minutes: z.number(),
          score: z.number(),
          rationale: z.string(),
        })),
        summary: z.string(),
        telemetry: z.object({
          prompt_version: z.string(),
          model_version: z.string(),
          fallback_used: z.boolean(),
          fallback_reason: z.string().optional(),
          retrieval_count: z.number(),
        }),
        quality: z.object({
          rubric: z.object({
            scores: z.array(z.object({
              category: z.enum(['grounding', 'clarity', 'actionability', 'safety']),
              score: z.number(),
              rationale: z.string(),
            })),
            overall_score: z.number(),
            band: z.enum(['high', 'medium', 'low']),
          }),
          sampled_for_review: z.boolean(),
          review_sample_id: z.string().optional(),
          sampling_reason: z.enum(['low_quality', 'random_sample']).optional(),
        }),
      }),
      422: z.object({
        success: z.literal(false),
        error: z.string(),
        safety: z.object({
          safe: z.boolean(),
          reason: z.string().optional(),
          matched_term: z.string().optional(),
        }).optional(),
      }),
      503: z.object({ success: z.literal(false), error: z.literal('feature_disabled') }),
    },
  },
  aiNegotiationPrepAssistant: {
    method: 'POST',
    path: '/api/ai/negotiation-prep',
    body: z.object({
      goals: z.array(z.string()),
      event_id: z.string().optional(),
      session_id: z.string().optional(),
      filters: z.object({
        borough: z.enum(['manhattan', 'brooklyn', 'queens', 'bronx', 'staten_island']).optional(),
        category: z.enum(['music', 'food', 'arts', 'networking', 'family', 'wellness']).optional(),
        max_price: z.number().optional(),
        starts_before_hour: z.number().optional(),
        within_walk_minutes: z.number().optional(),
      }).optional(),
      constraints: z.object({
        max_price: z.number().optional(),
        preferred_contact_channel: z.enum(['email', 'sms', 'phone']).optional(),
        must_haves: z.array(z.string()).optional(),
      }).optional(),
    }),
    responses: {
      200: z.object({
        success: z.literal(true),
        summary: z.string(),
        talking_points: z.array(z.string()),
        suggested_concessions: z.array(z.string()),
        red_flags: z.array(z.string()),
        opening_script: z.string(),
        context: z.object({
          event_id: z.string().optional(),
          title: z.string().optional(),
          borough: z.string().optional(),
          category: z.string().optional(),
          price: z.number().optional(),
        }),
        telemetry: z.object({
          prompt_version: z.string(),
          model_version: z.string(),
          fallback_used: z.boolean(),
          fallback_reason: z.string().optional(),
          retrieval_count: z.number(),
        }),
        quality: z.object({
          rubric: z.object({
            scores: z.array(z.object({
              category: z.enum(['grounding', 'clarity', 'actionability', 'safety']),
              score: z.number(),
              rationale: z.string(),
            })),
            overall_score: z.number(),
            band: z.enum(['high', 'medium', 'low']),
          }),
          sampled_for_review: z.boolean(),
          review_sample_id: z.string().optional(),
          sampling_reason: z.enum(['low_quality', 'random_sample']).optional(),
        }),
      }),
      422: z.object({
        success: z.literal(false),
        error: z.string(),
        safety: z.object({
          safe: z.boolean(),
          reason: z.string().optional(),
          matched_term: z.string().optional(),
        }).optional(),
      }),
      503: z.object({ success: z.literal(false), error: z.literal('feature_disabled') }),
    },
  },
  aiDocumentHelper: {
    method: 'POST',
    path: '/api/ai/document-helper',
    body: z.object({
      document_text: z.string(),
      listing_title: z.string().optional(),
      session_id: z.string().optional(),
      extraction_mode: z.enum(['summary_only', 'summary_and_checklist']).optional(),
    }),
    responses: {
      200: z.object({
        success: z.literal(true),
        summary: z.string(),
        checklist: z.array(z.object({
          item: z.string(),
          status: z.enum(['present', 'missing', 'unclear']),
          evidence: z.string().optional(),
        })),
        action_items: z.array(z.string()),
        telemetry: z.object({
          prompt_version: z.string(),
          model_version: z.string(),
          fallback_used: z.boolean(),
          fallback_reason: z.string().optional(),
          retrieval_count: z.number(),
        }),
        quality: z.object({
          rubric: z.object({
            scores: z.array(z.object({
              category: z.enum(['grounding', 'clarity', 'actionability', 'safety']),
              score: z.number(),
              rationale: z.string(),
            })),
            overall_score: z.number(),
            band: z.enum(['high', 'medium', 'low']),
          }),
          sampled_for_review: z.boolean(),
          review_sample_id: z.string().optional(),
          sampling_reason: z.enum(['low_quality', 'random_sample']).optional(),
        }),
      }),
      422: z.object({
        success: z.literal(false),
        error: z.string(),
        safety: z.object({
          safe: z.boolean(),
          reason: z.string().optional(),
          matched_term: z.string().optional(),
        }).optional(),
      }),
      503: z.object({ success: z.literal(false), error: z.literal('feature_disabled') }),
    },
  },
  listAiReviewSamples: {
    method: 'GET',
    path: '/api/ai/review-sampling/queue',
    responses: {
      200: z.object({
        success: z.literal(true),
        items: z.array(z.object({
          id: z.string(),
          feature: z.enum(['ai_concierge_chat', 'ai_shortlist_builder', 'ai_negotiation_prep_assistant', 'ai_document_helper']),
          output_type: z.string(),
          session_id: z.string().optional(),
          output_preview: z.string(),
          rubric: z.object({
            scores: z.array(z.object({
              category: z.enum(['grounding', 'clarity', 'actionability', 'safety']),
              score: z.number(),
              rationale: z.string(),
            })),
            overall_score: z.number(),
            band: z.enum(['high', 'medium', 'low']),
          }),
          sampling_reason: z.enum(['low_quality', 'random_sample']),
          status: z.enum(['pending', 'approved', 'needs_revision']),
          reviewer: z.string().optional(),
          notes: z.string().optional(),
          created_at: z.string(),
          updated_at: z.string(),
        })),
      }),
    },
  },
  decideAiReviewSample: {
    method: 'POST',
    path: '/api/ai/review-sampling/:sample_id/decision',
    body: z.object({
      decision: z.enum(['approved', 'needs_revision']),
      reviewer: z.string().optional(),
      notes: z.string().optional(),
    }),
    responses: {
      200: z.object({
        success: z.literal(true),
        item: z.object({
          id: z.string(),
          status: z.enum(['pending', 'approved', 'needs_revision']),
          updated_at: z.string(),
        }).passthrough(),
      }),
      404: z.object({ success: z.literal(false), error: z.literal('not_found') }),
      422: z.object({ success: z.literal(false), error: z.string() }),
    },
  },
  listAiFollowUpTemplates: {
    method: 'GET',
    path: '/api/ai/follow-up/templates',
    responses: {
      200: z.object({
        success: z.literal(true),
        items: z.array(z.object({
          id: z.string(),
          version: z.string(),
          name: z.string(),
          channel: z.enum(['email', 'sms', 'push']),
          body_template: z.string(),
        })),
      }),
      503: z.object({ success: z.literal(false), error: z.literal('feature_disabled') }),
    },
  },
  approveAiFollowUpTemplate: {
    method: 'POST',
    path: '/api/ai/follow-up/templates/:template_id/approve',
    body: z.object({
      recipient_id: z.string(),
      approved_by: z.string().optional(),
      template_version: z.string().optional(),
    }),
    responses: {
      200: z.object({
        success: z.literal(true),
        approval: z.object({
          recipient_id: z.string(),
          template_id: z.string(),
          template_version: z.string(),
          approved_by: z.string().optional(),
          approved_at: z.string(),
        }),
      }),
      404: z.object({ success: z.literal(false), error: z.literal('template_not_found') }),
      422: z.object({ success: z.literal(false), error: z.string() }),
      503: z.object({ success: z.literal(false), error: z.literal('feature_disabled') }),
    },
  },
  getAiSuppressionControls: {
    method: 'GET',
    path: '/api/ai/suppression-controls/:recipient_id',
    responses: {
      200: z.object({
        success: z.literal(true),
        controls: z.object({
          recipient_id: z.string(),
          quiet_hours_start: z.number(),
          quiet_hours_end: z.number(),
          frequency_cap_per_day: z.number(),
          opt_out: z.boolean(),
          updated_at: z.string(),
        }),
      }),
      422: z.object({ success: z.literal(false), error: z.string() }),
      503: z.object({ success: z.literal(false), error: z.literal('feature_disabled') }),
    },
  },
  upsertAiSuppressionControls: {
    method: 'POST',
    path: '/api/ai/suppression-controls',
    body: z.object({
      recipient_id: z.string(),
      quiet_hours_start: z.number().optional(),
      quiet_hours_end: z.number().optional(),
      frequency_cap_per_day: z.number().optional(),
      opt_out: z.boolean().optional(),
    }),
    responses: {
      200: z.object({
        success: z.literal(true),
        controls: z.object({
          recipient_id: z.string(),
          quiet_hours_start: z.number(),
          quiet_hours_end: z.number(),
          frequency_cap_per_day: z.number(),
          opt_out: z.boolean(),
          updated_at: z.string(),
        }),
      }),
      422: z.object({ success: z.literal(false), error: z.string() }),
      503: z.object({ success: z.literal(false), error: z.literal('feature_disabled') }),
    },
  },
  runAiFollowUpAutomation: {
    method: 'POST',
    path: '/api/ai/follow-up-automation',
    body: z.object({
      recipient_id: z.string(),
      template_id: z.string(),
      channel: z.enum(['email', 'sms', 'push']).optional(),
      session_id: z.string().optional(),
      send_at_hour: z.number().optional(),
      context: z.object({
        first_name: z.string().optional(),
        event_title: z.string(),
        next_step: z.string(),
        deadline: z.string().optional(),
      }),
    }),
    responses: {
      200: z.object({
        success: z.literal(true),
        dispatch: z.object({
          id: z.string(),
          recipient_id: z.string(),
          template_id: z.string(),
          template_version: z.string(),
          channel: z.enum(['email', 'sms', 'push']),
          message: z.string(),
          status: z.enum(['queued', 'suppressed']),
          suppression_reason: z.enum(['opt_out', 'quiet_hours', 'frequency_cap']).optional(),
          created_at: z.string(),
        }),
        suppression: z.object({
          recipient_id: z.string(),
          quiet_hours_start: z.number(),
          quiet_hours_end: z.number(),
          frequency_cap_per_day: z.number(),
          opt_out: z.boolean(),
          updated_at: z.string(),
        }).optional(),
      }),
      422: z.object({ success: z.literal(false), error: z.string() }),
      503: z.object({ success: z.literal(false), error: z.literal('feature_disabled') }),
    },
  },
  listAiFollowUpDispatches: {
    method: 'GET',
    path: '/api/ai/follow-up-automation/dispatches',
    query: z.object({
      recipient_id: z.string().optional(),
    }).optional(),
    responses: {
      200: z.object({
        success: z.literal(true),
        items: z.array(z.object({
          id: z.string(),
          recipient_id: z.string(),
          template_id: z.string(),
          template_version: z.string(),
          channel: z.enum(['email', 'sms', 'push']),
          message: z.string(),
          status: z.enum(['queued', 'suppressed']),
          suppression_reason: z.enum(['opt_out', 'quiet_hours', 'frequency_cap']).optional(),
          created_at: z.string(),
        })),
      }),
      503: z.object({ success: z.literal(false), error: z.literal('feature_disabled') }),
    },
  },
  aiNextBestAction: {
    method: 'POST',
    path: '/api/ai/next-best-action',
    body: z.object({
      recipient_id: z.string(),
      event_id: z.string().optional(),
      intent: z.string().optional(),
      session_id: z.string().optional(),
      send_at_hour: z.number().optional(),
      max_actions: z.number().optional(),
      funnel_stage: z.enum(['discovery', 'consideration', 'negotiation', 'ready_to_book', 'post_inquiry']).optional(),
      filters: z.object({
        borough: z.enum(['manhattan', 'brooklyn', 'queens', 'bronx', 'staten_island']).optional(),
        category: z.enum(['music', 'food', 'arts', 'networking', 'family', 'wellness']).optional(),
        max_price: z.number().optional(),
        starts_before_hour: z.number().optional(),
        within_walk_minutes: z.number().optional(),
      }).optional(),
      signals: z.object({
        shortlisted: z.boolean().optional(),
        inquiry_sent: z.boolean().optional(),
        schedule_requested: z.boolean().optional(),
        schedule_confirmed: z.boolean().optional(),
        docs_reviewed: z.boolean().optional(),
        price_drop_seen: z.boolean().optional(),
      }).optional(),
    }),
    responses: {
      200: z.object({
        success: z.literal(true),
        summary: z.string(),
        actions: z.array(z.object({
          id: z.enum(['book_now', 'schedule_visit', 'send_inquiry', 'request_discount', 'save_alert', 'ask_follow_up']),
          priority: z.number(),
          title: z.string(),
          reason: z.string(),
          suggested_channel: z.enum(['email', 'sms', 'push']),
          suppressed: z.boolean(),
          suppression_reason: z.enum(['opt_out', 'quiet_hours', 'frequency_cap']).optional(),
        })),
        suppression: z.object({
          recipient_id: z.string(),
          quiet_hours_start: z.number(),
          quiet_hours_end: z.number(),
          frequency_cap_per_day: z.number(),
          opt_out: z.boolean(),
          updated_at: z.string(),
        }),
        telemetry: z.object({
          prompt_version: z.string(),
          model_version: z.string(),
          fallback_used: z.boolean(),
          retrieval_count: z.number(),
        }),
      }),
      422: z.object({ success: z.literal(false), error: z.string() }),
      503: z.object({ success: z.literal(false), error: z.literal('feature_disabled') }),
    },
  },
  syncRealtimeAvailability: {
    method: 'POST',
    path: '/api/availability/sync',
    body: z.object({
      updates: z.array(z.object({
        event_id: z.string(),
        status: z.enum(['available', 'limited', 'sold_out']).optional(),
        seats_total: z.number().int().positive().optional(),
        seats_remaining: z.number().int().nonnegative().optional(),
        updated_at: z.string().optional(),
      })).min(1).max(100),
    }),
    responses: {
      200: z.object({
        success: z.literal(true),
        processed: z.number(),
        items: z.array(z.object({
          event_id: z.string(),
          status: z.enum(['available', 'limited', 'sold_out']),
          seats_total: z.number().optional(),
          seats_remaining: z.number().optional(),
          updated_at: z.string(),
        })),
      }),
      422: z.object({ success: z.literal(false), error: z.string() }),
      503: z.object({ success: z.literal(false), error: z.literal('feature_disabled') }),
    },
  },
  ingestAvailabilityWebhook: {
    method: 'POST',
    path: '/api/availability/webhook/:provider',
    body: z.object({
      records: z.array(z.object({
        id: z.string().optional(),
        event_id: z.string().optional(),
        status: z.enum(['available', 'limited', 'sold_out']).optional(),
        availability: z.enum(['available', 'limited', 'sold_out']).optional(),
        seats_total: z.number().int().positive().optional(),
        seats_remaining: z.number().int().nonnegative().optional(),
        seats: z.object({
          total: z.number().int().positive().optional(),
          remaining: z.number().int().nonnegative().optional(),
        }).optional(),
        updated_at: z.string().optional(),
      })).min(1).max(500),
      sent_at: z.string().optional(),
    }),
    responses: {
      200: z.object({
        success: z.literal(true),
        provider: z.string(),
        processed: z.number(),
        items: z.array(z.object({
          event_id: z.string(),
          status: z.enum(['available', 'limited', 'sold_out']),
          seats_total: z.number().optional(),
          seats_remaining: z.number().optional(),
          updated_at: z.string(),
        })),
      }),
      401: z.object({ success: z.literal(false), error: z.literal('unauthorized_webhook') }),
      422: z.object({ success: z.literal(false), error: z.string() }),
      503: z.object({
        success: z.literal(false),
        error: z.union([z.literal('feature_disabled'), z.literal('webhook_token_not_configured')]),
      }),
    },
  },
  getExperienceI18nByLocale: {
    method: 'GET',
    path: '/api/experience/i18n/:locale',
    responses: {
      200: z.object({
        success: z.literal(true),
        requested_locale: z.string(),
        resolved_locale: z.enum(['en-US', 'es-US', 'zh-CN']),
        rtl: z.boolean(),
        labels: z.object({
          smart_search_title: z.string(),
          smart_search_subtitle: z.string(),
          borough: z.string(),
          category: z.string(),
          max_price: z.string(),
          starts_before: z.string(),
          walk_distance: z.string(),
          search_button: z.string(),
        }),
        taxonomy: z.object({
          categories: z.object({
            music: z.string(),
            food: z.string(),
            arts: z.string(),
            networking: z.string(),
            family: z.string(),
            wellness: z.string(),
          }),
          boroughs: z.object({
            manhattan: z.string(),
            brooklyn: z.string(),
            queens: z.string(),
            bronx: z.string(),
            staten_island: z.string(),
          }),
        }),
      }),
      503: z.object({ success: z.literal(false), error: z.literal('feature_disabled') }),
    },
  },
  getExperienceI18n: {
    method: 'GET',
    path: '/api/experience/i18n',
    query: z.object({
      locale: z.string().optional(),
    }).optional(),
    responses: {
      200: z.object({
        success: z.literal(true),
        requested_locale: z.string().optional(),
        resolved_locale: z.enum(['en-US', 'es-US', 'zh-CN']),
        rtl: z.boolean(),
      }).passthrough(),
      503: z.object({ success: z.literal(false), error: z.literal('feature_disabled') }),
    },
  },
  getAccessibilityPreferences: {
    method: 'GET',
    path: '/api/experience/accessibility/preferences/:session_id',
    responses: {
      200: z.object({
        success: z.literal(true),
        preference: z.object({
          session_id: z.string(),
          high_contrast: z.boolean(),
          reduced_motion: z.boolean(),
          keyboard_first: z.boolean(),
          updated_at: z.string(),
        }),
      }),
      422: z.object({ success: z.literal(false), error: z.string() }),
      503: z.object({ success: z.literal(false), error: z.literal('feature_disabled') }),
    },
  },
  upsertAccessibilityPreferences: {
    method: 'POST',
    path: '/api/experience/accessibility/preferences',
    body: z.object({
      session_id: z.string(),
      high_contrast: z.boolean().optional(),
      reduced_motion: z.boolean().optional(),
      keyboard_first: z.boolean().optional(),
    }),
    responses: {
      200: z.object({
        success: z.literal(true),
        preference: z.object({
          session_id: z.string(),
          high_contrast: z.boolean(),
          reduced_motion: z.boolean(),
          keyboard_first: z.boolean(),
          updated_at: z.string(),
        }),
      }),
      422: z.object({ success: z.literal(false), error: z.string() }),
      503: z.object({ success: z.literal(false), error: z.literal('feature_disabled') }),
    },
  },
  ingestPartnerWebhookEvent: {
    method: 'POST',
    path: '/api/integrations/webhooks/:partner/events',
    body: z.object({
      event_id: z.string(),
      event_type: z.string(),
      occurred_at: z.string().optional(),
      payload: z.record(z.unknown()),
    }),
    responses: {
      202: z.object({
        success: z.literal(true),
        partner: z.string(),
        delivery_id: z.string(),
        accepted_at: z.string(),
        replay_protection: z.object({
          nonce: z.string(),
          max_skew_seconds: z.number(),
        }),
      }).passthrough(),
      401: z.object({ success: z.literal(false), error: z.string() }),
      409: z.object({ success: z.literal(false), error: z.literal('replay_detected') }),
      422: z.object({ success: z.literal(false), error: z.string() }),
      503: z.object({
        success: z.literal(false),
        error: z.union([z.literal('feature_disabled'), z.literal('webhook_secret_not_configured')]),
      }),
    },
  },
  listUserDashboards: {
    method: 'GET',
    path: '/api/dashboards',
    query: z.object({
      owner_id: z.string().optional(),
    }).optional(),
    responses: {
      200: z.object({
        success: z.literal(true),
        items: z.array(z.object({
          id: z.string(),
          owner_id: z.string(),
          name: z.string(),
          cards: z.array(z.object({
            id: z.string(),
            metric: z.enum(['search_queries', 'search_clicks', 'inquiries_submitted', 'schedules_confirmed', 'ai_conversions']),
            title: z.string(),
            visualization: z.enum(['kpi', 'line', 'bar']),
            window_days: z.number(),
          })),
          layout: z.object({
            columns: z.number(),
            density: z.enum(['comfortable', 'compact']),
          }),
          created_at: z.string(),
          updated_at: z.string(),
        })),
      }),
      422: z.object({ success: z.literal(false), error: z.string() }),
      503: z.object({ success: z.literal(false), error: z.literal('feature_disabled') }),
    },
  },
  saveUserDashboard: {
    method: 'POST',
    path: '/api/dashboards',
    body: z.object({
      owner_id: z.string(),
      dashboard_id: z.string().optional(),
      name: z.string(),
      cards: z.array(z.object({
        id: z.string(),
        metric: z.enum(['search_queries', 'search_clicks', 'inquiries_submitted', 'schedules_confirmed', 'ai_conversions']),
        title: z.string(),
        visualization: z.enum(['kpi', 'line', 'bar']),
        window_days: z.number(),
      })),
      layout: z.object({
        columns: z.number().optional(),
        density: z.enum(['comfortable', 'compact']).optional(),
      }).optional(),
    }),
    responses: {
      200: z.object({ success: z.literal(true), item: z.object({ id: z.string() }).passthrough() }),
      422: z.object({ success: z.literal(false), error: z.string() }),
      503: z.object({ success: z.literal(false), error: z.literal('feature_disabled') }),
    },
  },
  removeUserDashboard: {
    method: 'DELETE',
    path: '/api/dashboards/:dashboard_id',
    body: z.object({
      owner_id: z.string(),
    }),
    responses: {
      200: z.object({ success: z.literal(true), dashboard_id: z.string() }),
      404: z.object({ success: z.literal(false), error: z.literal('not_found') }),
      422: z.object({ success: z.literal(false), error: z.string() }),
      503: z.object({ success: z.literal(false), error: z.literal('feature_disabled') }),
    },
  },
  getInsightsHub: {
    method: 'GET',
    path: '/api/dashboards/insights/hub',
    query: z.object({
      window_days: z.string().optional(),
    }).optional(),
    responses: {
      200: z.object({
        success: z.literal(true),
        summary: z.object({
          window_days: z.number(),
          total_events: z.number(),
          active_sessions: z.number(),
          trend_direction: z.enum(['up', 'down', 'flat']),
        }),
      }).passthrough(),
      503: z.object({ success: z.literal(false), error: z.literal('feature_disabled') }),
    },
  },
  getPartnerWorkspaceRoles: {
    method: 'GET',
    path: '/api/partners/workspaces/:workspace_id/roles',
    responses: {
      200: z.object({
        success: z.literal(true),
        workspace_id: z.string(),
        role_templates: z.array(z.object({
          id: z.string(),
          name: z.string(),
          description: z.string(),
          permissions: z.array(z.string()),
        })),
        assignments: z.array(z.object({
          workspace_id: z.string(),
          member_id: z.string(),
          role_id: z.string(),
          assigned_by: z.string().optional(),
          assigned_at: z.string(),
        })),
      }),
      422: z.object({ success: z.literal(false), error: z.string() }),
      503: z.object({ success: z.literal(false), error: z.literal('feature_disabled') }),
    },
  },
  assignPartnerWorkspaceRole: {
    method: 'POST',
    path: '/api/partners/workspaces/:workspace_id/members/:member_id/role',
    body: z.object({
      role_id: z.enum(['workspace_admin', 'ops_manager', 'analyst', 'support_agent', 'viewer']),
      assigned_by: z.string().optional(),
    }),
    responses: {
      200: z.object({
        success: z.literal(true),
        assignment: z.object({
          workspace_id: z.string(),
          member_id: z.string(),
          role_id: z.string(),
          assigned_by: z.string().optional(),
          assigned_at: z.string(),
        }),
      }).passthrough(),
      422: z.object({ success: z.literal(false), error: z.string() }),
      503: z.object({ success: z.literal(false), error: z.literal('feature_disabled') }),
    },
  },
  getPartnerPortalConfig: {
    method: 'GET',
    path: '/api/partners/portals/:tenant_id/config',
    responses: {
      200: z.object({
        success: z.literal(true),
        config: z.object({
          tenant_id: z.string(),
          brand_name: z.string(),
          theme: z.object({
            primary_color: z.string(),
            accent_color: z.string(),
            logo_url: z.string().optional(),
          }),
          feature_overrides: z.record(z.boolean()),
          updated_at: z.string(),
        }),
      }),
      422: z.object({ success: z.literal(false), error: z.string() }),
      503: z.object({ success: z.literal(false), error: z.literal('feature_disabled') }),
    },
  },
  upsertPartnerPortalConfig: {
    method: 'PUT',
    path: '/api/partners/portals/:tenant_id/config',
    body: z.object({
      brand_name: z.string().optional(),
      theme: z.object({
        primary_color: z.string().optional(),
        accent_color: z.string().optional(),
        logo_url: z.string().optional(),
      }).optional(),
      feature_overrides: z.record(z.boolean()).optional(),
    }),
    responses: {
      200: z.object({ success: z.literal(true), config: z.object({ tenant_id: z.string() }).passthrough() }),
      422: z.object({ success: z.literal(false), error: z.string() }),
      503: z.object({ success: z.literal(false), error: z.literal('feature_disabled') }),
    },
  },
  listPartnerPilotRollout: {
    method: 'GET',
    path: '/api/partners/pilot/rollout',
    responses: {
      200: z.object({
        success: z.literal(true),
        phases: z.array(z.object({
          phase: z.enum(['sandbox_validation', 'staging_dry_run', 'limited_production', 'general_availability']),
          status: z.enum(['pending', 'in_progress', 'completed']),
          checklist: z.array(z.string()),
          updated_at: z.string(),
        })),
      }),
      503: z.object({ success: z.literal(false), error: z.literal('feature_disabled') }),
    },
  },
  updatePartnerPilotRollout: {
    method: 'POST',
    path: '/api/partners/pilot/rollout',
    body: z.object({
      phase: z.enum(['sandbox_validation', 'staging_dry_run', 'limited_production', 'general_availability']),
      status: z.enum(['pending', 'in_progress', 'completed']),
    }),
    responses: {
      200: z.object({
        success: z.literal(true),
        phase: z.object({
          phase: z.enum(['sandbox_validation', 'staging_dry_run', 'limited_production', 'general_availability']),
          status: z.enum(['pending', 'in_progress', 'completed']),
          checklist: z.array(z.string()),
          updated_at: z.string(),
        }),
        phases: z.array(z.object({
          phase: z.enum(['sandbox_validation', 'staging_dry_run', 'limited_production', 'general_availability']),
          status: z.enum(['pending', 'in_progress', 'completed']),
          checklist: z.array(z.string()),
          updated_at: z.string(),
        })),
      }),
      404: z.object({ success: z.literal(false), error: z.literal('not_found') }),
      422: z.object({ success: z.literal(false), error: z.string() }),
      503: z.object({ success: z.literal(false), error: z.literal('feature_disabled') }),
    },
  },
  submitLead: {
    method: 'POST',
    path: '/api/leads',
    body: z.object({
      email: z.string().email(),
      source_cta: z.string().optional(),
      source_section: z.string().optional(),
      use_case: z.enum(['consumer_discovery', 'business_listing', 'marketing_analytics', 'agency_partnership']).optional(),
      team_size: z.enum(['solo', 'small_2_10', 'mid_11_50', 'enterprise_50_plus']).optional(),
      city: z.string().max(100).optional(),
      borough: z.enum(['manhattan', 'brooklyn', 'queens', 'bronx', 'staten_island']).optional(),
      goal: z.string().max(180).optional(),
    }),
    responses: {
      201: z.object({
        success: z.literal(true),
        id: z.number(),
        follow_up: z.object({
          route: z.enum(['community_waitlist', 'self_serve_onboarding', 'marketing_consult', 'sales_demo', 'partnership_review']),
          priority: z.enum(['standard', 'high']),
          automation_status: z.enum(['queued', 'not_configured', 'failed']),
          automation_provider: z.string(),
        }),
      }),
      409: z.object({ success: z.literal(false), error: z.literal('email_exists') }),
      422: z.object({ success: z.literal(false), error: z.string() }),
    },
  },
  joinWaitlist: {
    method: 'POST',
    path: '/api/waitlist',
    body: z.object({
      email: z.string().email(),
      zip_code: z.string().optional(),
      city: z.string().optional(),
      use_case: z.enum(['consumer_discovery', 'business_listing', 'marketing_analytics', 'agency_partnership']).optional(),
      team_size: z.enum(['solo', 'small_2_10', 'mid_11_50', 'enterprise_50_plus']).optional(),
      goal: z.string().max(180).optional(),
    }),
    responses: {
      201: z.object({
        success: z.literal(true),
        follow_up: z.object({
          route: z.enum(['community_waitlist', 'self_serve_onboarding', 'marketing_consult', 'sales_demo', 'partnership_review']),
          priority: z.enum(['standard', 'high']),
          automation_status: z.enum(['queued', 'not_configured', 'failed']),
          automation_provider: z.string(),
        }),
      }),
      422: z.object({ success: z.literal(false), error: z.string() }),
    },
  },
  logAnalyticsEvent: {
    method: 'POST',
    path: '/api/analytics/events',
    body: z.object({
      event_name: z.enum([
        'cta_click',
        'section_view',
        'faq_expand',
        'pricing_tab_view',
        'search_query',
        'search_result_click',
        'inquiry_started',
        'inquiry_submitted',
        'schedule_requested',
        'schedule_conflict',
        'schedule_confirmed',
        'ai_concierge_prompt',
        'ai_concierge_response',
        'ai_shortlist_generated',
        'ai_fallback_triggered',
        'ai_negotiation_prep_generated',
        'ai_document_helper_generated',
        'ai_quality_sampled',
        'ai_quality_review_decision',
        'ai_follow_up_automation_run',
        'ai_next_best_action_generated',
        'ux_locale_applied',
        'accessibility_mode_updated',
        'insights_hub_view',
        'partner_ops_view',
        'onboarding_defaults_applied',
        'waitlist_route_preview_updated',
        'waitlist_submit_attempted',
        'waitlist_submit_succeeded',
        'marketing_snapshot_automation_applied',
        'marketing_snapshot_playbook_intake_opened',
        'marketing_snapshot_playbook_step_updated',
        'marketing_snapshot_recovery_query_run',
        'marketing_snapshot_recovery_escalation_run',
        'marketing_snapshot_tuning_rule_applied',
        'contact_playbook_route_reconciled',
        'contact_goal_template_applied',
        'contact_form_draft_restored',
      ]),
      properties: z.record(z.unknown()).optional(),
      session_id: z.string().optional(),
    }),
    responses: {
      204: z.undefined(),
      422: z.object({ success: z.literal(false), error: z.string() }),
    },
  },
});
